changelog:
  exclude:
    authors:
      - dependabot
      - pre-commit-ci
  categories:
    - title: Bugs fixes 🐛
      labels:
        - bug
    - title: Features and enhancements 🎉
      labels:
        - enhancement
    - title: Tooling and packaging 🔧
      labels:
        - ci-cd
    - title: Documentation 📖
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
