blank_issues_enabled: true
contact_links:
  - name: Ask, answer, share
    url: https://github.com/Guts/DicoGIS/discussions/
    about: Have a question or need help? Have an answer or idea to share? Connect with the community on our discussion board
  - name: Support DicoGIS development or want to use it in your organization?
    url: https://guts.github.io/DicoGIS/misc/funding.html
    about: Want to contract to use DicoGIS in your organization or to fund or sponsor a feature or a bug fix?
