name: dicogis-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - nomkl
  - gdal=3.1.3
  - pip
  - pyinstaller>=3.6,<4.2
  - setuptools
  - wheel
  - pip:
    - -r file:base.txt
    - -r file:dev.txt
