name: dicogis-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal=3.1.3
  - numpy=1.19.3
  - pip
  - pyinstaller>=3.6,<4.1
  - setuptools
  - wheel
  - pip:
    - -r file:base.txt
    - -r file:dev.txt
