name: dicogis-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - nomkl
  - gdal=3.4.3
  - pip
  - pyinstaller>=5
  - setuptools
  - wheel
  - pip:
      - -r file:base.txt
      - -r file:development.txt
