name: Windows Builder

on:
  push:
    branches: [ master ]

env:
  GDAL_VERSION: 3.1.3
  PROJECT_FOLDER: "dicogis"
  PYTHON_VERSION: 3.8
  PYINSTALLER_LOG_LEVEL: "DEBUG"

jobs:
  build-windows:

    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v1
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('requirements/conda-env-dev.yml') }}

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v1.7.0
      with:
        activate-environment: dicogis-dev
        channels: conda-forge,defaults
        channel-priority: true
        environment-file: requirements/conda-env-dev.yml
        mamba-version: "*"
        python-version: ${{ env.PYTHON_VERSION }}
        use-only-tar-bz2: true

    - name: Install project as a package
      run: python -m pip install -e .

    - name: Generates MS Version Info
      run: python .\builder\version_info_templater.py

    - name: Generates MS Executable
      run: python -O .\builder\pyinstaller_build_windows.py

    - name: Zip generated application folder
      uses: papeloto/action-zip@v1
      with:
        files: dist/DicoGIS
        dest: DicoGIS_windows_64bits.zip

    - name: Save it as artifact
      uses: actions/upload-artifact@v2
      with:
        name: DicoGIS_windows_executable
        path: DicoGIS_windows_64bits.zip
