name: "📚 Documentation Builder"

on:
  push:
    branches: [master]
    paths:
      - "docs/**/*"
      - ".github/workflows/docs_builder.yml"
      - "dicogis/**/*.py"

env:
  GDAL_VERSION: 3.*
  PYTHON_VERSION: "3.10"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: "requirements/documentation.txt"

      - name: Install GDAL binaries
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable && sudo apt-get update
          sudo apt install gdal-bin=${{ env.GDAL_VERSION }}
          sudo apt install libgdal-dev=${{ env.GDAL_VERSION }}
          export CPLUS_INCLUDE_PATH=/usr/include/gdal
          export C_INCLUDE_PATH=/usr/include/gdal
          gdal-config --version

      - name: Install complementary tools
        run: |
          sudo apt install python3-tk

      - name: Install project requirements
        run: |
          python -m pip install -U pip setuptools wheel
          # Install GDAL first
          python -m pip install GDAL=="`gdal-config --version`.*"
          # then project
          python -m pip install -U -r requirements/base.txt
          python -m pip install -U -r requirements/development.txt
          python -m pip install -U -r requirements/documentation.txt
          python -m pip install -U ghp-import>2

      - name: Install project as a package
        run: python -m pip install -e .

      - name: Build doc using Sphinx
        run: sphinx-build -b html -d docs/_build/cache -j auto -q docs docs/_build/html

      - name: Deploy to GitHub Pages
        run: ghp-import --force --no-history --no-jekyll --push docs/_build/html
