name: Documentation Builder

on:
  push:
    branches: [ master ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container: osgeo/gdal:alpine-normal-latest
    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Ensure pip is installed
      run: apk add py3-pip

    - name: Install dependencies
      run: python -m pip install -U -r requirements/docs.txt

    - name: Build doc using Sphinx
      run: sphinx-build -b html docs docs/_build
