name: Documentation Builder

on:
  push:
    branches: [master]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container: osgeo/gdal:ubuntu-normal-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Ensure pip is installed
        run: apk add py3-pip

      - name: Caching pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U -r requirements/base.txt
          python -m pip install -U -r requirements/dev.txt
          python -m pip install -U -r requirements/docs.txt

      - name: Build doc using Sphinx
        run: sphinx-build -b html docs docs/_build
