name: Quick Linter

on:
  pull_request:
    branches: [ master ]

env:
  URL_GDAL_CORE: https://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-3-0-4-mapserver-7-4-3/gdal-300-1911-x64-core.msi
  URL_GDAL_PYTHON: https://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-3-0-4-mapserver-7-4-3/GDAL-3.0.4.win-amd64-py3.7.msi
  PATH_GDAL_INSTALL: ${{ github.workspace }}\GDAL_INSTALL

jobs:
  lint-windows:

    runs-on: windows-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Prepare 
      run: mkdir ${{ env.PATH_GDAL_INSTALL }}

    - name: Download GDAL Core for Windows
      uses: carlosperate/download-file-action@v1.0.3
      id: download-gdal-core
      with:
        # URL of the file to download
        file-url: ${{ env.URL_GDAL_CORE }}
        # New filename to rename the downloaded file
        file-name: gdal-core.msi
        location: "."

    - name: Install GDAL Core
      run: |
        msiexec /i gdal-core.msi INSTALLDIR="${{ env.PATH_GDAL_INSTALL }}" /quiet

    - name: Download GDAL Python bindings for Windows
      uses: carlosperate/download-file-action@v1.0.3
      id: download-gdal-py-bindings
      with:
        # URL of the file to download
        file-url: ${{ env.URL_GDAL_PYTHON }}
        # New filename to rename the downloaded file
        file-name: gdal-python-bindings.msi
        location: "."

    - name: Install GDAL Python Bindings
      run: |
        msiexec /i ./gdal-python-bindings.msi INSTALLDIR="${{ env.PATH_GDAL_INSTALL }}" /quiet

    - name: Add GDAL to the path
      run: echo "${{ env.PATH_GDAL_INSTALL }}" >> $GITHUB_PATH

    - name: Add GDAL DATA as environment variable
      run: echo "GDAL_DATA=${{ env.PATH_GDAL_INSTALL }}/gdal-data" >> $GITHUB_ENV

    - name: Display GDAL installation folder
      run: |
        ls ${{ env.PATH_GDAL_INSTALL }}

    # - name: Cache pip
    #   # https://github.com/actions/cache/blob/master/examples.md#python---pip
    #   uses: actions/cache@v1
    #   with:
    #     path: ~\AppData\Local\pip\Cache # This path is specific to Windows
    #     # Look to see if there is a cache hit for the corresponding requirements file
    #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements/base.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    #       ${{ runner.os }}-

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip setuptools wheel
    #     python -m pip install -r requirements/dev.txt

    - name: Install Python GDAL
      env:
        GDAL_DATA: "${{ env.PATH_GDAL_INSTALL }}\gdal-data"
      run: |
        gdalinfo --version
    #     # python -m pip install gdal==3.0.*

    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings.
    #     flake8 . --count --exit-zero --statistics
